"""
E-Challan PDF generation with QR code
Tamil Nadu Motor Vehicles Act compliant
"""

import os
import qrcode
from datetime import datetime
from typing import Dict, Optional
from io import BytesIO

from fpdf import FPDF
from PIL import Image


class ChallanPDF(FPDF):
    """Custom PDF class for TN e-challan"""
    
    def header(self):
        # Tamil Nadu Government Header
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'GOVERNMENT OF TAMIL NADU', 0, 1, 'C')
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, 'TRANSPORT DEPARTMENT', 0, 1, 'C')
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'E-CHALLAN (Electronic Challan)', 0, 1, 'C')
        self.ln(5)
        
        # Separator line
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by SARAL-TN on {datetime.now().strftime("%d-%m-%Y %H:%M:%S")}', 0, 0, 'C')


class ChallanGenerator:
    """Generate legally valid e-challans"""
    
    def __init__(self):
        self.offense_codes = {
            "red_light_jump": {"section": "119/177 MVA", "fine": 1000},
            "wrong_side_driving": {"section": "177 MVA", "fine": 1500},
            "no_helmet": {"section": "129/177 MVA", "fine": 500},
            "triple_riding": {"section": "128/177 MVA", "fine": 1000},
            "illegal_parking": {"section": "122/177 MVA", "fine": 500},
        }
    
    def generate(self, violation_data: Dict, output_path: Optional[str] = None) -> bytes:
        """
        Generate PDF challan
        
        Args:
            violation_data: Dict with violation details
            output_path: Where to save (optional)
        
        Returns:
            PDF as bytes
        """
        pdf = ChallanPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Challan Details
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, f'Challan Number: {violation_data["challan_id"]}', 0, 1)
        pdf.cell(0, 10, f'Date & Time: {violation_data["datetime"]}', 0, 1)
        pdf.ln(5)
        
        # Vehicle Details
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'VEHICLE DETAILS', 0, 1)
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 8, f'Registration Number: {violation_data["plate_number"]}', 0, 1)
        pdf.cell(0, 8, f'Vehicle Class: {violation_data.get("vehicle_class", "Motor Cycle/Car")}', 0, 1)
        pdf.cell(0, 8, f'Owner Name: {violation_data.get("owner_name", "As per RTO records")}', 0, 1)
        pdf.ln(5)
        
        # Violation Details
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'VIOLATION DETAILS', 0, 1)
        pdf.set_font('Arial', '', 11)
        
        offense = self.offense_codes.get(violation_data["violation_type"], {})
        
        pdf.cell(0, 8, f'Offense: {violation_data["violation_type"].replace("_", " ").title()}', 0, 1)
        pdf.cell(0, 8, f'Section: {offense.get("section", "177 MVA")}', 0, 1)
        pdf.cell(0, 8, f'Location: {violation_data.get("location", "Chennai, TN")}', 0, 1)
        pdf.cell(0, 8, f'GPS: {violation_data.get("gps", "N/A")}', 0, 1)
        pdf.ln(5)
        
        # Evidence
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'EVIDENCE', 0, 1)
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 8, f'Video Evidence ID: {violation_data["video_hash"][:16]}...', 0, 1)
        pdf.cell(0, 8, f'AI Confidence: {violation_data.get("confidence", "N/A")}%', 0, 1)
        pdf.cell(0, 8, f'Reported by: Citizen ID {violation_data["reporter_id"][:8]}...', 0, 1)
        pdf.ln(10)
        
        # Fine Details (Highlighted)
        pdf.set_fill_color(230, 230, 230)
        pdf.set_font('Arial', 'B', 14)
        fine_amount = offense.get("fine", 1000)
        pdf.cell(0, 12, f'TOTAL FINE AMOUNT: Rs. {fine_amount}/-', 0, 1, 'C', True)
        pdf.ln(10)
        
        # Payment Instructions
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'PAYMENT OPTIONS', 0, 1)
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 8, '1. Online: https://echallan.tn.gov.in', 0, 1)
        pdf.cell(0, 8, '2. UPI: saral-tn@axisbank', 0, 1)
        pdf.cell(0, 8, '3. RTO Office: Greater Chennai Traffic Police', 0, 1)
        pdf.ln(5)
        
        # QR Code
        qr_data = f"CHALLAN:{violation_data['challan_id']}|AMT:{fine_amount}|TN"
        qr_img = self._generate_qr(qr_data)
        
        # Save QR temporarily
        with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as tmp:
            qr_img.save(tmp.name)
            pdf.image(tmp.name, x=80, w=50)
            os.unlink(tmp.name)
        
        pdf.ln(5)
        pdf.set_font('Arial', 'I', 10)
        pdf.cell(0, 10, 'Scan QR code to pay online instantly', 0, 1, 'C')
        
        # Legal Notice
        pdf.ln(10)
        pdf.set_font('Arial', '', 9)
        pdf.multi_cell(0, 5, 
            'Disclaimer: This e-challan is generated through SARAL-TN, an AI-powered '
            'traffic enforcement system approved by the Government of Tamil Nadu. '
            'The violation has been recorded via citizen reporting with video evidence. '
            'If you believe this challan was issued incorrectly, you may file an appeal '
            'within 15 days at the nearest RTO office or online portal.'
        )
        
        # Output
        if output_path:
            pdf.output(output_path)
        
        # Return as bytes
        pdf_bytes = pdf.output(dest='S').encode('latin1')
        return pdf_bytes
    
    def _generate_qr(self, data: str) -> Image.Image:
        """Generate QR code image"""
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_H,
            box_size=10,
            border=4,
        )
        qr.add_data(data)
        qr.make(fit=True)
        
        img = qr.make_image(fill_color="black", back_color="white")
        return img


# Global instance
challan_gen = ChallanGenerator()
